#!/usr/bin/env python3
# Convenience script to run urlwatch from a Git checkout
# This is NOT the script that gets installed as part of "setup.py install"

import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), 'lib'))
from urlwatch.cli import main
main()
