.TH URLWATCH "1" "January 2019" "urlwatch 2.16" "User Commands"
.SH NAME
urlwatch \- monitors webpages for you
.SH SYNOPSIS
.B urlwatch [options]
.SH DESCRIPTION
urlwatch is intended to help you watch changes in webpages and get notified
(via e\-mail, in your terminal or through various third party services) of any
changes. The change notification will include the URL that has changed and
a unified diff of what has changed.
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
show debug output
.SS "files and directories:"
.TP
\fB\-\-urls\fR FILE
read job list (URLs) from FILE
.TP
\fB\-\-config\fR FILE
read configuration from FILE
.TP
\fB\-\-hooks\fR FILE
use FILE as hooks.py module
.TP
\fB\-\-cache\fR FILE
use FILE as cache database
.SS "Authentication:"
.TP
\fB\-\-smtp\-login\fR
Enter password for SMTP (store in keyring)
.TP
\fB\-\-telegram\-chats\fR
List telegram chats the bot is joined to
.TP
\fB\-\-test\-slack\fR
Send a test notification to Slack
.SS "job list management:"
.TP
\fB\-\-list\fR
list jobs
.TP
\fB\-\-add\fR JOB
add job (key1=value1,key2=value2,...)
.TP
\fB\-\-delete\fR JOB
delete job by location or index
.TP
\fB\-\-test\-filter\fR JOB
test filter output of job by location or index
.SS "interactive commands ($EDITOR/$VISUAL):"
.TP
\fB\-\-edit\fR
edit URL/job list
.TP
\fB\-\-edit\-config\fR
edit configuration file
.TP
\fB\-\-edit\-hooks\fR
edit hooks script
.SS "miscellaneous:"
.TP
\fB\-\-features\fR
list supported jobs/filters/reporters
.TP
\fB\-\-gc\-cache\fR
remove old cache entries
.SH "FILES"
.TP
.B $XDG_CONFIG_HOME/urlwatch/urls.yaml
A list of URLs, commands and other jobs to watch
.TP
.B $XDG_CONFIG_HOME/urlwatch/hooks.py
A Python module that can implement new job types, filters and reporters
.TP
.B $XDG_CACHE_HOME/urlwatch/cache.db
A SQLite 3 database that contains the state history of jobs (for diffing)
.SH AUTHOR
Thomas Perl <thp.io/about>
.SH WEBSITE
https://thp.io/2008/urlwatch/
