name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt
        python -m pip install pycodestyle==2.6.0 pytest
        sudo apt install -y build-essential libpoppler-cpp-dev pkg-config python3-dev tesseract-ocr
        python -m pip install pdftotext docutils pygments pytesseract pillow jq
    - name: Test with pytest
      run: pytest -v
